<!--
THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.

Copyright (c) Microsoft Corporation. All rights reserved
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <script src="/js/3_CatchingErrors.js"></script>
</head>
<body>
    <div data-win-control="SdkSample.ScenarioInput">
        <p>
            Promises support error handling. By passing a second callback
            function to the then() method, an error handler can be specified
            that will be called if an exception occurs during the promise's
            execution.
        </p>
        <button class="action catchingErrorsButton">Catch A Thrown Error</button>
    </div>
    <div data-win-control="SdkSample.ScenarioOutput">
        <p class="catchingErrorsOutput"></p>
    </div>
</body>
</html>
